# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: core

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_USERNAME: redis
      REDIS_PASSWORD: example
      REDIS_ACL: |
        user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ~* +@all
    command: >
      sh -c "echo \"$REDIS_ACL\" > /usr/local/etc/redis/aclfile &&
      redis-server --aclfile /usr/local/etc/redis/aclfile"
