name: Generate docs

on:
  workflow_call:

jobs:
  swagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
          check-latest: true
          cache: true

      - name: Install Taskfile
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Install dependencies
        run: task install

      - name: Generate docs
        run: task docs

      - name: Export docs
        uses: actions/upload-artifact@v4
        with:
          name: swagger
          path: |
            docs/swagger.yml
            docs/swagger.json
