name: Deploy Prod

on:
  release:
    types: [ released ]

concurrency:
  group: "release-deploy"
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/_test_build.yml

  docs:
    uses: ./.github/workflows/_generate_docs.yml
